### ISSUE TITLE
Use Suspenders to generate a Rails Project

### ISSUE THREAD

**Issue by kirillian** [kirillian/oil_change_reminder#1]
# Suspenders
### Why use Suspenders at all?
Suspenders is a Rails template that includes a lot of standard Rails gems already baked in and is ready to deploy to Heroku. While you may not want all of these gems, you probably will want almost all of them, MOST of the time. For someone who is trying to stand an app up quickly, knowing how to use a tool like Suspenders is invaluable. The great thing about tools like this is that you can always swap something out if you don't like it.

### Prerequisites Checklist
- [ ] Install Postgresql
- [ ] Make sure you have Chrome installed
- [ ] Make sure you have Ruby 2.6.3 installed

### Instructions
Follow instructions here on the Suspenders page: https://github.com/thoughtbot/suspenders

Summary of instructions here (assuming you are in this project's directory):
```bash
gem install suspenders
suspenders .
```
If Suspenders asks to overwrite a file, go ahead and tell it yes (`Y`).

**Comment by lrogers1843** [comment]
complete!
